### ISSUE TITLE
Resolve Polars `columns` deprecation warning

### ISSUE THREAD

**Issue by jsstevenson** [GenomicMedLab/cool-seq-tool#289] opened 2024-06-10 12:54 UTC
```
/Users/jss009/code/metakb/.venv/lib/python3.12/site-packages/cool_seq_tool/mappers/mane_transcript.py:553: DeprecationWarning: named `columns` param is deprecated; use positional `*args` instead.
    copy_df = copy_df.drop(columns="alt_ac").unique()
```

**Comment by korikuzma** [comment] 2024-06-10 12:56
Duplicate of #267

**Closed by korikuzma** 2024-06-10 12:56 UTC
Labels: priority:medium, technical debt
